lunarmodules/terminal.lua

- src/terminal/init.lua
Title: Fix oldunpack issue in init.lua for Lua 5.1 compatibility
Description:
This PR fixes an issue where oldunpack wasn’t properly set in init.lua, causing errors in Lua 5.1. The fix ensures _G.oldunpack correctly falls back to _G.unpack or table.unpack, preventing compatibility issues.
Before Changes:
print(oldunpack)
>nil
Changes made:
Updated init.lua to use _G.oldunpack = _G.unpack or table.unpack for Lua 5.1 compatibility.
Testing:
Verified in Lua 5.1, confirming that the error no longer occurs.
> Fix oldunpack issue in init.lua for Lua 5.1 compatibility

- examples/colors.lua
- spec/03-clear_spec.lua
- src/terminal/clear.lua
Removes redundancy (terminal.clear.clear() → terminal.clear.screen())
Singular function names for better readability (clear_top() → top())
Consistent suffixes (_seq) to differentiate ANSI sequence functions
solves issue #24
> Refactor terminal.clear API for better readability

- src/terminal/init.lua
- src/terminal/scroll/stack.lua
if we pass in `math.huge` the loop becomes infinite, but the calculation does not.
> fix(scroll-stack): fix inifinite loop

- spec/04-scroll_spec.lua
- src/terminal/init.lua
- src/terminal/scroll/init.lua
- src/terminal/utils.lua
This PR introduces support for negative indices in the terminal library, following Lua’s convention. Changes include:
- Added `resolve_index` helper function to convert negative indices.
- Added `get_height` and `get_width` for terminal dimensions.
- Updated cursor positioning (`cursor_set`, `cursor_sets`) to handle negative indices.
- Updated `scroll_region` to support negative indices.
Related Issue: Closes #34
> Add Support for Negative Indices (Closes #34)

- spec/02-input_spec.lua
- src/terminal/init.lua
- src/terminal/input.lua
- src/terminal/output.lua
this simplifies the configuration.
Instead of having the functions in multiple places (input and output) and methods to set them. They ar now only on the main module, set when initializing.
> refactor(sleep): set sleep functions only on main module

- spec/00-utils_spec.lua
- spec/04-scroll_spec.lua
- spec/05-scroll_stack_spec.lua
- spec/06-cursor_spec.lua
- src/terminal/cursor/position/init.lua
- src/terminal/scroll/init.lua
- src/terminal/scroll/stack.lua
- src/terminal/utils.lua
> fix(indices): range check indices and add tests

- src/terminal/init.lua
consistent with 'cursor.visible'
Each function now takes a boolean parameter, which defaults to `true`. So:
```lua
terminal.blink()       -- turn blink on
terminal.blink(false)  -- turn blink off
terminal.blink(true)   -- turn blink on
```
fixes #44
> fix(textattr): make function singular with argument

- src/terminal/draw/init.lua
- src/terminal/init.lua
- src/terminal/progress.lua
- src/terminal/text/width.lua
allows to preload spinner utf-8 characters and box-drawing characters into the width cache.
Also renames test function;
- `text.width.width_test_write` -> `text.width.test_write`
- `text.width.width_test` -> `text.width.test`
> feat(width): add function to preload known graphical chars

- examples/colors.lua
- examples/progress.lua
- src/terminal/init.lua
It now only rethrows if there actually was an error.
> fix(initwrap): initwrap is now transparent

- src/terminal/init.lua
getting the cursor position may fail if the terminal doesn't support it. Hence we need to use a pcall to prevent it from failing and NOT restoring terminal settings.
> fix(shutdown): better errorhandling to be more sturdy

- examples/testscreen.lua
- src/terminal/output.lua
Output remains unreliable in general. Lua doesn't return the
successfully written byte-count, hence no way to proper retry.
The only way is to write 1 byte at a time, and flush every
write operation.
Very inefficient it seems, but no better way so far.
> chore(example): rewrite example to test writing

- examples/async.lua
- spec/02-input_spec.lua
- src/terminal/input.lua
Due to typo sys.sleep was still used.
> fix(input): proper sleep method is now used

- examples/menu.lua
This commit adds a new example, IMenu, that demonstrates how to create an interactive IMenu in the terminal using arrow keys, 'j'/'k', and Enter for selection.
The example allows users to add choices, navigate with up/down keys, and select an option. It utilizes ANSI sequences for cursor control and visual feedback.
This example will help users learn how to create interactive command line tools using the terminal library.
> docs(example) add interactive menu example

- examples/testscreen.lua
- src/terminal/init.lua
- src/terminal/output.lua
- terminal-scm-1.rockspec
ensure output streams remain blocking.
This relies on https://github.com/lunarmodules/luasystem/pull/59
> fix(output): use new system.detachfds

- spec/00-utils_spec.lua
- src/terminal/cli/select.lua
- src/terminal/utils.lua
ancestor methods/props are copied now for performance, to remove
the lookup chain.
upon instantiating, self is no longer passed in, but an options
table.
> refactor(class): remove lookup chain, remove self

- examples/cow.lua
- spec/06-cursor_spec.lua
- src/terminal/cursor/position/stack.lua
Moo! I was making a cow example and wonder, ? why is `cursor.position.stack.push` has signature 
```
cursor.position.stack.push(row, col)
```
and not just 
``` 
cursor.position.stack.push()
```
Looking at `examples/sequence`, I would see how having the parameters help with moving the cursor, but I imagine most use cases of `push` wouldn't need to do that (as in cow example) 
My fix: remove the two parameters and use result from `position.get()` instead
> Cow example and cursor position stack

- spec/09-utf8edit_spec.lua
- src/terminal/cli/prompt.lua
- src/terminal/utf8edit.lua
This PR: 
- implements `opts.position` for prompt to set intial cursor position 
- word navigation and word text editing for `utf8edit` and `prompt`
tracks #117
> feat(prompt): finish prompt advanced keybindings

- spec/09-editline-format_spec.lua
- src/terminal/editline.lua
If the cursor was at the very end of a string, but not past the width, it would still insert an extra line when formatting.
> fix(editline): no newline if cursor within range on last line

- spec/06-cursor_spec.lua
- src/terminal/cursor/position/init.lua
Since relative movements are often calculated, 0 is now a valid input, and does nothing for the up/down/left/right functions.
> fix(cursor): left/right/up/down now take 0 as a valid value

- spec/09-editline-format_spec.lua
- src/terminal/editline.lua
Opening brackets associate to the right, hence wordwrap shouldn't break on those. See the adjusted test case for an example.
> fix(editline): opening brackets associate right, don't break

- spec/09-editline-format_spec.lua
- src/terminal/editline.lua
width needs to be minimal 2 to format and have double-width chars. first-line width can be less, we simply move everything to the next line.
> fix(editline): when formatting firstline can have width < 2
